import type { Metadata } from "next";
import { Receipt } from "lucide-react";
import { Menu } from "lucide-react";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "../components/shared/sidebar";
import { MobileHeader } from "@/components/shared/mobileHeader";
import { ThemeProvider } from "@/components/themeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full">
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans flex h-screen overflow-hidden bg-background antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

        {/* DESKTOP SIDEBAR */}
        <aside className="hidden lg:flex w-64 border-r ">
          <Sidebar />
        </aside>

        <main className="flex-1 flex flex-col min-w-0 overflow-hidden">
          {/* MOBILE HEADER - Clean & Hydration Safe */}
          <MobileHeader />

          {/* PAGE CONTENT */}
          <div className="flex-1 overflow-y-auto p-4 md:p-8">
            <div className="max-w-7xl mx-auto">
              {children}
            </div>
          </div>
        </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
